name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.8

  flutter_launcher_icons: ^0.13.1 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/cloudy.json
    - assets/animations/sunny.json
    - assets/animations/rainy.json
    - assets/animations/snow.json
    - assets/animations/wind.json
    - assets/animations/humidity.json

# 👇 Move flutter_icons out of the flutter: section
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  remove_alpha_ios: true
